record_types = {
   Impression = 1,            -- Impression \sa NGADataPacket
   Click = 2,                 -- Click \sa NGLDataPacket
   View = 3,                  -- True count (view) \sa NTCDataPacket
   Bid = 4,                   -- Bid \sa NBIDDataPacket
   Block = 5,                 -- Block (e.g. referring URL)
   Conversion = 6,            -- Conversion (postclick) \sa NCNVDataPacket
   Pixel = 7,                 -- Pixel (beacon)
   Video = 8,                 -- Video \sa NAVDataPacket
   Event = 9,                 -- RichMediaAvroPacket
   MalwareScan = 10,          -- MalwareScanPacket
   Passback = 11,             -- PassbackPacket
   CookieValue = 12,          -- CVDataAvroPacket
   KeyValue = 13,             -- KVDataAvroPacket
   MobileImpression = 14,     -- Mobile Impression
   MobileClick = 15,          -- Mobile Click
   Keyword = 16,              -- KeywordDataAvroPacket
   PostClick = 17,            -- PostClickAvroPacket
   BadPostClick = 18,         -- BadPostClickAvroPacket
   Advisibility = 19,         -- AdvisAvroPacket
   EcpmResponse = 20,         -- EcpmResponsePackage
   UserTracking = 21,         -- UserTrackingAvroPacket
   ClickFraud = 22,           -- ClickFraudAvroPacket
   InvalidRequest = 23,       -- InvalidRequestAvroPacket
   PerformanceData = 24,      -- PerformanceDataAvroPacket
   UnknownUserAgent = 25,     -- UnknownUserAgentAvroPacket
   Uts = 26,                  -- UTSAvroPacket
   FilteredClick = 27,        -- SGSAvroFilteredClickPacket
   QoSInternalIP = 29,        -- QoSInternalIPAvroPacket
   QoSBlockedRequest = 30,    -- QoSBlockReqAvroPacket
   QoSUserAgent = 31,         -- QoSUserAgentAvroPacket
   PassbackV2 = 32,           -- Passback 2.0 record (same schema as NBID)
   PubAPIRequest = 33,        -- PubAPI Request record (same schema as NBID)
   PubAPIWinNotification = 34 -- PubAPIWinNotification record
}
